AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ApexDomainName:
    Type: String
  OriginBucketName:
    Type: String
  OriginId:
    Type: String
  CertificateArn:
    Type: String

Resources:
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront OAI for ${ApexDomainName}'
  OriginBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref OriginBucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  OriginBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref OriginBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Join [ "", [ "arn:aws:s3:::", !Ref OriginBucket, "/*" ] ]
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref ApexDomainName
          - !Sub 'www.${ApexDomainName}'
        Enabled: true
        Origins:
          - Id: !Ref OriginId
            DomainName: !Sub  '${OriginBucket}.s3.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Join
                - ''
                - - origin-access-identity/cloudfront/
                  - !Ref OriginAccessIdentity
#        CustomErrorResponses:
#          - ErrorCachingMinTTL: 300
#            ErrorCode: 403
#            ResponseCode: 200
#            ResponsePagePath: /index.html
#          - ErrorCachingMinTTL: 300
#            ErrorCode: 404
#            ResponseCode: 200
#            ResponsePagePath: /index.html
        PriceClass: PriceClass_All
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Ref OriginId
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only

Outputs:
  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName
  DistributionId:
    Value: !Ref Distribution