AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  StackTimeout:
    Type: String
    Default: 60
  DomainName:
    Type: String
  BranchName:
    Type: String
  RepositoryName:
    Type: String
  GitHubOwner:
    Type: String
  GitHubSecret:
    Type: String
    NoEcho: true
  GitHubOAuthToken:
    Type: String
    NoEcho: true
  CertificateArn:
    Type: String
Resources:
  CloudFront:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ApexDomainName: !Ref DomainName
        OriginBucketName: !Ref DomainName
        OriginId: !Ref DomainName
        CertificateArn: !Ref CertificateArn
#        CertificateArn: !Ref Certificate
      TemplateURL: ./cloudfront.yaml
      TimeoutInMinutes: !Ref StackTimeout
  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DistributionId: !GetAtt CloudFront.Outputs.DistributionId
        DeployBucket: !Ref DomainName
        BranchName: !Ref BranchName
        RepositoryName: !Ref RepositoryName
        GitHubOwner: !Ref GitHubOwner
        GitHubSecret: !Ref GitHubSecret
        GitHubOAuthToken: !Ref GitHubOAuthToken
      TemplateURL: ./codepipeline.yaml
  Route53:
    Type: AWS::CloudFormation::Stack
    DependsOn: CloudFront
    Properties:
      Parameters:
        DomainName: !Ref DomainName
        CloudFrontUrl: !GetAtt CloudFront.Outputs.DistributionDomainName
      TemplateURL: ./route53.yaml
#  Certificate:
#    Type: AWS::CertificateManager::Certificate
#    Properties:
#      DomainName: !Ref DomainName
#      SubjectAlternativeNames:
#        - !Sub '*.${DomainName}'
#      ValidationMethod: DNS